version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pos
    volumes:
      - db_data:/var/lib/postgresql/data
    ports: ["5432:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    volumes:
      - minio_data:/data
    ports: ["9000:9000", "9001:9001"]

  backend:
    build: ../apps/backend
    env_file:
      - ../apps/backend/.env.example
    depends_on: [db, redis, minio]
    ports: ["4000:4000"]

  frontend:
    build: ../apps/frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    depends_on: [backend]
    ports: ["3000:3000"]

volumes:
  db_data:
  minio_data:
